#DDL

DROP TABLE CUSTOMERS 

CREATE TABLE CUSTOMERS(
   ID   NUMBER                 NOT NULL,
   FIRST_NAME VARCHAR2(20)     NOT NULL,
   LAST_NAME VARCHAR2(20)     NOT NULL
   AGE  NUMBER                NOT NULL,
   ADDRESS  VARCHAR2(25) ,
   PRIMARY KEY (ID));


ALTER TABLE CUSTOMERS
ADD  SALARY   NUMBER ;

#DML
INSERT INTO CUSTOMERS (ID,FIRST_NAME,LAST_NAME,AGE,ADDRESS,SALARY)
VALUES (1,'ALI','ALIYEV',23,'AZADLIQ PROSPEKTI',800); COMMIT

INSERT INTO CUSTOMERS (ID,FIRST_NAME,LAST_NAME,AGE,ADDRESS,SALARY)
VALUES (2,'SABINA','RZAYEVA',21,'XATAI M',750); COMMIT

INSERT INTO CUSTOMERS (ID,FIRST_NAME,LAST_NAME,AGE,ADDRESS,SALARY)
VALUES (3,'SADIQ','QAFAROV',26,'28 MAY M',1000); COMMIT

INSERT INTO CUSTOMERS (ID,FIRST_NAME,LAST_NAME,AGE,ADDRESS,SALARY)
VALUES (4,'ELVIRA','YUSIFOVA',29,'HAZI ASLANOV',900); COMMIT

UPDATE CUSTOMERS 
SET  SALARY=740
WHERE FIRST_NAME='SADIQ' AND ID=3
COMMIT;


DELETE CUSTOMERS 
WHERE AGE=30
COMMIT;

#SELECT STATEMENT 
SELECT * FROM EMPLOYEES

SELECT FIRST_NAME, LAST_NAME
FROM EMPLOYEES 
WHERE SALARY > 5000 AND JOB_ID='SH_CLERK'
ORDER BY FIRST_NAME 


SELECT DEPARTMENT_ID  
FROM EMPLOYEES 
GROUP BY DEPARTMENT_ID
HAVING COUNT(EMPLOYEE_ID) >4
FETCH FIRST 5 ROWS ONLY 


#SINGLE ROW FUNCTIONS
 
 SELECT UPPER(FIRST_NAME),LOWER(LAST_NAME)
 FROM EMPLOYEES

SELECT INITCAP(DEPARTMENT_NAME)
FROM EMPLOYEES

SELECT CONCAT('ALI','YUNUSZADE'),LENGTH('GSADHGSD'), TRIM('    A  ')
FROM DUAL

SELECT ROUND(1235,-2),TRUNC(35436,2), ABS(-4),MOD(34,6),SQRT(25)
FROM DUAL 


SELECT SYSDATE,EXTRACT(YEAR FROM SYSDATE)
FROM DUAL

#AGGREGATE

SELECT COUNT(EMPLOYEE_ID),SUM(SALARY),MIN(SALARY),MAX(SALARY),AVG(SALARY),MEDIAN(SALARY)
FROM EMPLOYEES 

SELECT DEPARTMENT_ID,AVG(SALARY)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID

#CONVERSION FUNCTIONS






